name: Flask-First testing
run-name: ${{ github.actor }} is testing Flask-First
on: [push]
jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
    - run: |
        make format
  test:
    runs-on: ubuntu-latest
    steps:
    - run: make test
  build:
    runs-on: ubuntu-latest
    steps:
    - run: make build
